[package]
name = "project_management"
version = "0.9.1"
edition = "2021"
description = "Power-CLI project management tool with hierarchical task organisation and a retro-rapid TUI."
license = "MIT"
authors = ["Peter Garfield Bower"]
readme = "README.md"
repository = "https://github.com/pbower/project_management"
keywords = ["cli", "tui", "project-management", "task", "terminal"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = "0.29"
crossterm = "0.29"

[[bin]]
name = "pm"
path = "src/main.rs"
