//! Artifact index for each ticket's `artifacts/` directory.
//!
//! Every ticket has an `artifacts/` directory underneath it where humans and
//! agents drop reference material (PNGs, CSVs, PDFs, notes). The directory
//! also carries an `ARTIFACTS.md` index file that:
//!
//! - Lists every file present, with hand-curated descriptions and tags.
//! - Is regenerated by [`sweep`] on every relevant change.
//! - Preserves human edits to `desc`/`tags` for files that still exist.
//!
//! The on-disk shape:
//!
//! ```markdown
//! ---
//! generated_by: pm
//! last_swept: 2026-05-12T09:14:22Z
//! node: TSK7
//! ---
//!
//! # Artifacts (TSK7 - lock-protocol)
//!
//! - file: schema.png
//!   desc: ER diagram of the lock-file format
//!   tags: [reference, design]
//!   added: 2026-05-10
//!
//! - file: bench.csv
//!   desc: ''
//!   tags: []
//!   added: 2026-05-12
//! ```

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};

use super::front_matter::{split_front_matter, FrontMatterError};
use super::id::LeafId;
use super::state::atomic_write;

/// Filename of the per-ticket artifact index.
pub const ARTIFACTS_MD: &str = "ARTIFACTS.md";

/// One artifact entry. `desc` and `tags` are hand-curated and survive
/// sweeps; `file` and `added` are filesystem-derived on first scan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactEntry {
    /// File name relative to the `artifacts/` directory.
    pub file: String,
    /// Free-form description. Empty string means "not yet described".
    #[serde(default)]
    pub desc: String,
    /// Free-form tags for filtering.
    #[serde(default)]
    pub tags: Vec<String>,
    /// Date the file first appeared in the sweep.
    pub added: NaiveDate,
}

/// On-disk front-matter for an `ARTIFACTS.md` file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct ArtifactsFrontMatter {
    #[serde(default = "default_generated_by")]
    generated_by: String,
    last_swept: DateTime<Utc>,
    node: LeafId,
}

fn default_generated_by() -> String {
    "pm".to_string()
}

/// The parsed `ARTIFACTS.md` file: front-matter plus the entry list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArtifactsIndex {
    pub node: LeafId,
    pub last_swept: DateTime<Utc>,
    pub entries: Vec<ArtifactEntry>,
}

impl ArtifactsIndex {
    /// Build a fresh empty index for `node`.
    pub fn new(node: LeafId) -> Self {
        ArtifactsIndex {
            node,
            last_swept: Utc::now(),
            entries: Vec::new(),
        }
    }

    /// Look up an entry by file name. Case-sensitive.
    pub fn find(&self, file: &str) -> Option<&ArtifactEntry> {
        self.entries.iter().find(|e| e.file == file)
    }

    /// Mutable lookup by file name.
    pub fn find_mut(&mut self, file: &str) -> Option<&mut ArtifactEntry> {
        self.entries.iter_mut().find(|e| e.file == file)
    }

    /// Parse the contents of an `ARTIFACTS.md` file.
    pub fn parse(raw: &str) -> Result<Self, ArtifactError> {
        let (yaml, body) = split_front_matter(raw).map_err(ArtifactError::FrontMatter)?;
        let fm: ArtifactsFrontMatter =
            serde_yaml_ng::from_str(yaml).map_err(ArtifactError::Yaml)?;
        let entries = parse_entries(body)?;
        Ok(ArtifactsIndex {
            node: fm.node,
            last_swept: fm.last_swept,
            entries,
        })
    }

    /// Load from `<artifacts_dir>/ARTIFACTS.md`.
    pub fn load(index_path: &Path) -> Result<Self, ArtifactError> {
        let raw = fs::read_to_string(index_path).map_err(ArtifactError::Io)?;
        Self::parse(&raw)
    }

    /// Render to the full file contents, including a heading derived from
    /// the node's `LeafId`.
    pub fn render(&self) -> Result<String, ArtifactError> {
        let fm = ArtifactsFrontMatter {
            generated_by: "pm".into(),
            last_swept: self.last_swept,
            node: self.node,
        };
        let yaml = serde_yaml_ng::to_string(&fm).map_err(ArtifactError::Yaml)?;
        let heading = format!("# Artifacts ({})", self.node);
        let mut out = String::new();
        out.push_str("---\n");
        out.push_str(yaml.trim_end_matches('\n'));
        out.push_str("\n---\n\n");
        out.push_str(&heading);
        out.push_str("\n\n");
        if self.entries.is_empty() {
            // Leave the heading section empty rather than emit an empty YAML
            // sequence (`[]`) which reads as noise.
        } else {
            let entries_yaml =
                serde_yaml_ng::to_string(&self.entries).map_err(ArtifactError::Yaml)?;
            out.push_str(entries_yaml.trim_end_matches('\n'));
            out.push('\n');
        }
        Ok(out)
    }

    /// Atomic write to `<artifacts_dir>/ARTIFACTS.md`.
    pub fn save(&self, index_path: &Path) -> Result<(), ArtifactError> {
        if let Some(parent) = index_path.parent() {
            fs::create_dir_all(parent).map_err(ArtifactError::Io)?;
        }
        let rendered = self.render()?;
        atomic_write(index_path, rendered.as_bytes()).map_err(ArtifactError::Io)
    }

    /// Reconcile the index against the on-disk contents of `artifacts_dir`.
    /// Files present on disk but missing from the index are added with empty
    /// `desc`/`tags` and `added` set to today. Entries whose files no longer
    /// exist are removed. Files that exist at both sides keep their human
    /// metadata untouched. `last_swept` is updated.
    pub fn sweep(&mut self, artifacts_dir: &Path) -> Result<SweepReport, ArtifactError> {
        let on_disk = list_artifact_files(artifacts_dir)?;
        let on_disk_set: BTreeMap<&str, ()> = on_disk.iter().map(|f| (f.as_str(), ())).collect();

        // Index existing entries by file name for O(1) survival lookup.
        let mut existing: BTreeMap<String, ArtifactEntry> = std::mem::take(&mut self.entries)
            .into_iter()
            .map(|e| (e.file.clone(), e))
            .collect();

        let mut report = SweepReport::default();
        let today = Utc::now().date_naive();

        // Walk in alphabetical order so the on-disk output is deterministic.
        for file in &on_disk {
            if let Some(entry) = existing.remove(file) {
                self.entries.push(entry);
                report.kept.push(file.clone());
            } else {
                self.entries.push(ArtifactEntry {
                    file: file.clone(),
                    desc: String::new(),
                    tags: Vec::new(),
                    added: today,
                });
                report.added.push(file.clone());
            }
        }
        // Anything left in `existing` was in the previous index but is no
        // longer on disk.
        for (file, _) in existing {
            if !on_disk_set.contains_key(file.as_str()) {
                report.removed.push(file);
            }
        }
        self.last_swept = Utc::now();
        Ok(report)
    }
}

/// Counts of changes from a sweep run.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct SweepReport {
    pub added: Vec<String>,
    pub removed: Vec<String>,
    pub kept: Vec<String>,
}

impl SweepReport {
    /// True if no files were added, kept, or removed.
    pub fn is_empty(&self) -> bool {
        self.added.is_empty() && self.removed.is_empty() && self.kept.is_empty()
    }

    /// Whether any file delta occurred (added or removed).
    pub fn has_changes(&self) -> bool {
        !self.added.is_empty() || !self.removed.is_empty()
    }
}

/// Load (or create) the index, sweep it, save back. Returns the sweep report
/// and the updated index.
pub fn sweep_dir(
    artifacts_dir: &Path,
    node: LeafId,
) -> Result<(SweepReport, ArtifactsIndex), ArtifactError> {
    fs::create_dir_all(artifacts_dir).map_err(ArtifactError::Io)?;
    let index_path = artifacts_dir.join(ARTIFACTS_MD);
    let mut index = if index_path.exists() {
        ArtifactsIndex::load(&index_path)?
    } else {
        ArtifactsIndex::new(node)
    };
    let report = index.sweep(artifacts_dir)?;
    index.save(&index_path)?;
    Ok((report, index))
}

/// Rename an artifact file on disk and update its entry in the index in one
/// atomic-ish step. The `desc`, `tags`, and `added` fields carry over; only
/// the `file` field changes. Errors if the source is missing or the target
/// already exists.
pub fn rename_artifact(artifacts_dir: &Path, old: &str, new: &str) -> Result<(), ArtifactError> {
    let old_path = artifacts_dir.join(old);
    let new_path = artifacts_dir.join(new);
    if !old_path.exists() {
        return Err(ArtifactError::NotFound(old.to_string()));
    }
    if new_path.exists() {
        return Err(ArtifactError::TargetExists(new.to_string()));
    }
    let index_path = artifacts_dir.join(ARTIFACTS_MD);
    let mut index = if index_path.exists() {
        ArtifactsIndex::load(&index_path)?
    } else {
        // We need the node id to write a fresh index, and we have no source
        // for it here. Tell the caller to sweep first.
        return Err(ArtifactError::NoIndexForRename);
    };

    if let Some(entry) = index.find_mut(old) {
        entry.file = new.to_string();
    }
    fs::rename(&old_path, &new_path).map_err(ArtifactError::Io)?;
    index.last_swept = Utc::now();
    index.save(&index_path)?;
    Ok(())
}

/// List artifact file names (basename only) under `artifacts_dir`. Excludes
/// `ARTIFACTS.md` itself, dotfiles, and subdirectories. Sorted alphabetically.
fn list_artifact_files(artifacts_dir: &Path) -> Result<Vec<String>, ArtifactError> {
    let mut files: Vec<String> = Vec::new();
    if !artifacts_dir.exists() {
        return Ok(files);
    }
    for dirent in fs::read_dir(artifacts_dir).map_err(ArtifactError::Io)? {
        let dirent = dirent.map_err(ArtifactError::Io)?;
        let file_type = dirent.file_type().map_err(ArtifactError::Io)?;
        if !file_type.is_file() {
            continue;
        }
        let name = dirent.file_name().to_string_lossy().into_owned();
        if name == ARTIFACTS_MD || name.starts_with('.') {
            continue;
        }
        files.push(name);
    }
    files.sort();
    Ok(files)
}

/// Strip the leading h1 heading line and parse the remaining body as a YAML
/// sequence of entries. An empty body or one with only the heading parses to
/// an empty Vec.
fn parse_entries(body: &str) -> Result<Vec<ArtifactEntry>, ArtifactError> {
    let mut without_heading = String::new();
    let mut skipped_heading = false;
    for line in body.lines() {
        if !skipped_heading {
            let trimmed = line.trim_start();
            if trimmed.starts_with("# ") {
                skipped_heading = true;
                continue;
            }
            // Allow blank lines before the heading.
            if !trimmed.is_empty() {
                // No heading found; treat the line as part of the YAML body.
                without_heading.push_str(line);
                without_heading.push('\n');
            }
            continue;
        }
        without_heading.push_str(line);
        without_heading.push('\n');
    }
    let yaml = without_heading.trim();
    if yaml.is_empty() {
        return Ok(Vec::new());
    }
    let entries: Vec<ArtifactEntry> = serde_yaml_ng::from_str(yaml).map_err(ArtifactError::Yaml)?;
    Ok(entries)
}

/// All ways artifact operations can fail.
#[derive(Debug)]
pub enum ArtifactError {
    Io(io::Error),
    Yaml(serde_yaml_ng::Error),
    FrontMatter(FrontMatterError),
    NotFound(String),
    TargetExists(String),
    /// Caller asked to rename via [`rename_artifact`] but no ARTIFACTS.md
    /// exists yet; sweep first so the index can be built.
    NoIndexForRename,
}

impl std::fmt::Display for ArtifactError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ArtifactError::Io(e) => write!(f, "artifact io: {e}"),
            ArtifactError::Yaml(e) => write!(f, "artifact yaml: {e}"),
            ArtifactError::FrontMatter(e) => write!(f, "artifact front-matter: {e}"),
            ArtifactError::NotFound(s) => write!(f, "artifact not found: {s}"),
            ArtifactError::TargetExists(s) => write!(f, "rename target already exists: {s}"),
            ArtifactError::NoIndexForRename => write!(f, "no ARTIFACTS.md present; sweep first"),
        }
    }
}

impl std::error::Error for ArtifactError {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::id::TypePrefix;
    use std::path::PathBuf;

    fn tmp_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "pm-store-artifacts-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn task_leaf() -> LeafId {
        LeafId::new(TypePrefix::Task, 7)
    }

    #[test]
    fn render_round_trip_empty() {
        let idx = ArtifactsIndex::new(task_leaf());
        let raw = idx.render().unwrap();
        assert!(raw.contains("# Artifacts (TSK7)"));
        let back = ArtifactsIndex::parse(&raw).unwrap();
        assert_eq!(back.node, task_leaf());
        assert!(back.entries.is_empty());
    }

    #[test]
    fn render_round_trip_with_entries() {
        let mut idx = ArtifactsIndex::new(task_leaf());
        idx.entries.push(ArtifactEntry {
            file: "schema.png".into(),
            desc: "ER diagram of the lock-file format".into(),
            tags: vec!["reference".into(), "design".into()],
            added: NaiveDate::from_ymd_opt(2026, 5, 10).unwrap(),
        });
        idx.entries.push(ArtifactEntry {
            file: "bench.csv".into(),
            desc: String::new(),
            tags: vec![],
            added: NaiveDate::from_ymd_opt(2026, 5, 12).unwrap(),
        });
        let raw = idx.render().unwrap();
        let back = ArtifactsIndex::parse(&raw).unwrap();
        assert_eq!(back.entries.len(), 2);
        assert_eq!(back.entries[0].file, "schema.png");
        assert_eq!(back.entries[0].desc, "ER diagram of the lock-file format");
        assert_eq!(
            back.entries[0].tags,
            vec!["reference".to_string(), "design".to_string()]
        );
        assert_eq!(back.entries[1].desc, "");
    }

    #[test]
    fn sweep_adds_new_files() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("schema.png"), b"PNG").unwrap();
        fs::write(artifacts.join("bench.csv"), b"a,b").unwrap();

        let (report, idx) = sweep_dir(&artifacts, task_leaf()).unwrap();
        assert_eq!(report.added.len(), 2);
        assert!(report.removed.is_empty());
        assert_eq!(idx.entries.len(), 2);
        // Alphabetical order on disk: bench.csv, schema.png.
        assert_eq!(idx.entries[0].file, "bench.csv");
        assert_eq!(idx.entries[1].file, "schema.png");
        // All new entries get today's date and empty desc/tags.
        for e in &idx.entries {
            assert!(e.desc.is_empty());
            assert!(e.tags.is_empty());
        }
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn sweep_preserves_hand_curated_metadata() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("schema.png"), b"PNG").unwrap();

        // First sweep registers the file.
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();
        // Hand-edit the description in the index.
        let index_path = artifacts.join(ARTIFACTS_MD);
        let mut idx = ArtifactsIndex::load(&index_path).unwrap();
        idx.find_mut("schema.png").unwrap().desc = "ER diagram".into();
        idx.find_mut("schema.png").unwrap().tags = vec!["reference".into()];
        idx.save(&index_path).unwrap();

        // Second sweep should not blow away the hand-edits.
        let (_, idx_after) = sweep_dir(&artifacts, task_leaf()).unwrap();
        assert_eq!(idx_after.find("schema.png").unwrap().desc, "ER diagram");
        assert_eq!(
            idx_after.find("schema.png").unwrap().tags,
            vec!["reference".to_string()]
        );
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn sweep_drops_removed_files() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("schema.png"), b"PNG").unwrap();
        fs::write(artifacts.join("bench.csv"), b"a,b").unwrap();
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();

        // Delete bench.csv from disk.
        fs::remove_file(artifacts.join("bench.csv")).unwrap();
        let (report, idx) = sweep_dir(&artifacts, task_leaf()).unwrap();
        assert_eq!(report.removed, vec!["bench.csv".to_string()]);
        assert!(idx.find("bench.csv").is_none());
        assert!(idx.find("schema.png").is_some());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn sweep_ignores_artifacts_md_and_dotfiles_and_subdirs() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        // Things that should be ignored:
        fs::write(artifacts.join(".DS_Store"), b"").unwrap();
        fs::create_dir_all(artifacts.join("nested")).unwrap();
        fs::write(artifacts.join("nested").join("inside.txt"), b"x").unwrap();
        // Real artifact:
        fs::write(artifacts.join("real.csv"), b"a,b").unwrap();

        let (_, idx) = sweep_dir(&artifacts, task_leaf()).unwrap();
        let files: Vec<&str> = idx.entries.iter().map(|e| e.file.as_str()).collect();
        assert_eq!(files, vec!["real.csv"]);
        // Sanity: the ARTIFACTS.md we just wrote is not itself a registered entry.
        assert!(idx.find(ARTIFACTS_MD).is_none());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn rename_preserves_description() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("old.png"), b"PNG").unwrap();
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();

        let index_path = artifacts.join(ARTIFACTS_MD);
        let mut idx = ArtifactsIndex::load(&index_path).unwrap();
        idx.find_mut("old.png").unwrap().desc = "Worth keeping".into();
        idx.find_mut("old.png").unwrap().tags = vec!["design".into()];
        idx.save(&index_path).unwrap();

        rename_artifact(&artifacts, "old.png", "new.png").unwrap();
        assert!(!artifacts.join("old.png").exists());
        assert!(artifacts.join("new.png").exists());

        let after = ArtifactsIndex::load(&index_path).unwrap();
        let entry = after.find("new.png").expect("new entry present");
        assert_eq!(entry.desc, "Worth keeping");
        assert_eq!(entry.tags, vec!["design".to_string()]);
        assert!(after.find("old.png").is_none());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn rename_rejects_missing_source() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("real.png"), b"x").unwrap();
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();

        let err = rename_artifact(&artifacts, "ghost.png", "new.png").unwrap_err();
        assert!(matches!(err, ArtifactError::NotFound(_)));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn rename_rejects_existing_target() {
        let dir = tmp_dir();
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("a.png"), b"a").unwrap();
        fs::write(artifacts.join("b.png"), b"b").unwrap();
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();

        let err = rename_artifact(&artifacts, "a.png", "b.png").unwrap_err();
        assert!(matches!(err, ArtifactError::TargetExists(_)));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn concurrent_sweeps_produce_intact_file() {
        // Two threads repeatedly sweep the same artifacts/ directory while a
        // third thread alternates adding and removing files. The final file
        // must always be a valid ARTIFACTS.md (atomic write keeps reads
        // consistent).
        use std::sync::Arc;
        use std::thread;
        let dir = Arc::new(tmp_dir());
        let artifacts = dir.join("artifacts");
        fs::create_dir_all(&artifacts).unwrap();
        fs::write(artifacts.join("a.txt"), b"a").unwrap();
        let _ = sweep_dir(&artifacts, task_leaf()).unwrap();

        let stop = Arc::new(std::sync::atomic::AtomicBool::new(false));
        let mut handles = Vec::new();
        for _ in 0..2 {
            let artifacts = artifacts.clone();
            let stop = stop.clone();
            handles.push(thread::spawn(move || {
                while !stop.load(std::sync::atomic::Ordering::Relaxed) {
                    let _ = sweep_dir(&artifacts, task_leaf());
                }
            }));
        }
        // File churn thread.
        let artifacts2 = artifacts.clone();
        let stop2 = stop.clone();
        handles.push(thread::spawn(move || {
            let mut n = 0u32;
            while !stop2.load(std::sync::atomic::Ordering::Relaxed) {
                let p = artifacts2.join(format!("file-{}.txt", n % 4));
                if p.exists() {
                    let _ = fs::remove_file(&p);
                } else {
                    let _ = fs::write(&p, b"x");
                }
                n = n.wrapping_add(1);
            }
        }));
        std::thread::sleep(std::time::Duration::from_millis(150));
        stop.store(true, std::sync::atomic::Ordering::Relaxed);
        for h in handles {
            let _ = h.join();
        }

        // Final file should be parseable - never a torn read.
        let index_path = artifacts.join(ARTIFACTS_MD);
        ArtifactsIndex::load(&index_path)
            .expect("ARTIFACTS.md must remain valid under concurrent sweeps");
        fs::remove_dir_all(&*dir).ok();
    }
}
